# Generated by Django 2.2.2 on 2019-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5000)),
                ('lesson_description', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
